# Generated by Django 5.1 on 2024-09-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_moodentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kelas',
        ),
    ]
