# Generated by Django 5.1.1 on 2024-09-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_product_image_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
