# Generated by Django 5.1.1 on 2024-10-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_categories_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
